# The name of this file can be anyting but needs to be .yml
name: Test

# Whenever someone pushes to branch main then run the following job.
on:
  push:
    branches:
      - main
      - development
  pull_request: # push
    branches:
      - main
      - development

# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
jobs:
  build: # The name of job is arbitrary.
    # The actual name used here is important because it allows us to search for
    # the correct status check when Requiring status checks to pass before merging.
    # This is set up in GitHub branch --> Settings --> Branches.
    name: Build, Lint & Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm ci
      - name: Build Project
        run: npm run build --if-present
      - name: Lint src
        run: npm run lint
      - name: Run Tests
        run: npm test:run
